### ISSUE TITLE
Copyright on the buttom

### ISSUE THREAD

**Issue by dmpetrov** [dmpetrov/dmpetrov.github.io#10]
It should look like:
"© 2017 dataversioncontrol.com - info@dataversioncontrol.com - Blog - @FullStackML" 
The last is a clickable link to my personal twitter https://twitter.com/FullStackML
The one before the last is a link to blog.dataversioncontrol.com

All other links are not needed: about, archive etc.

Example (not exactly the same):
https://jn.gl/hello

**Comment by glozhkovoy** [comment]
Done.
<img width="1094" alt="screen shot 2017-04-19 at 06 46 44" src="https://cloud.githubusercontent.com/assets/20016615/25162505/f8a3a418-24cb-11e7-8e00-547443e8ac58.png">
