### ISSUE TITLE
Iterative machine learning picture and sentence

### ISSUE THREAD

**Issue by dmpetrov** [dmpetrov/dmpetrov.github.io#28]
We need a special block or page with this sentence:
"DVC helps you to iterate through your machine learning process in a simple way"

And a picture from my blog\tutorial post:
https://blog.dataversioncontrol.com/dvc-tutorial-iterative-machine-learning-9cf234a167cb

It might be in a separate page in multi-pages UI (#24).

**Comment by glozhkovoy** [comment]
Done
