### ISSUE TITLE
Anti-spam message in the subscribe form

### ISSUE THREAD

**Issue by dmpetrov** [dmpetrov/dmpetrov.github.io#5]
A small message is needed in the bottom of the form: "Up to 2 emails per month. No spam."

**Comment by glozhkovoy** [comment]
Changed.
<img width="493" alt="screen shot 2017-04-19 at 06 48 02" src="https://cloud.githubusercontent.com/assets/20016615/25162525/292b9104-24cc-11e7-84b8-e7b27717d794.png">
