### ISSUE TITLE
Browser icon

### ISSUE THREAD

**Issue by dmpetrov** [dmpetrov/dmpetrov.github.io#7]
Let's use Pinterest browser icon for now.

**Comment by glozhkovoy** [comment]
Try to clear the cache or open the page in another browser. Currently we are using custom Pinterest favicon.
<img width="371" alt="screen shot 2017-04-19 at 06 49 16" src="https://cloud.githubusercontent.com/assets/20016615/25162543/590c74ce-24cc-11e7-9855-f3dc518821ff.png">

**Comment by dmpetrov** [comment]
It dissipated. It looks like it was a browser cache issue.
