### ISSUE TITLE
Beta version

### ISSUE THREAD

**Issue by dmpetrov** [dmpetrov/dmpetrov.github.io#9]
It should be clear that this is only Beta version. On the Download button or close by.

Possible messages: 
- "DVC beta version 0.8 is available now"
- "Download beta version"

**Comment by glozhkovoy** [comment]
<img width="279" alt="screen shot 2017-04-19 at 07 08 38" src="https://cloud.githubusercontent.com/assets/20016615/25162932/1b62970e-24cf-11e7-9208-576d57aa99b3.png">
